services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=media_net
    networks:
      - media_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ${CONF_PATH}/caddy:/data
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/lidarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 8686:8686  
    networks:
      - media_net
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /lidarr*
      caddy.handle.reverse_proxy: "{{upstreams 8686}}"
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONF_PATH}/qbittorrent:/config
      - ${DATA_PATH}:/data
    ports:
      - 8080:8080 # Temporary for setup
    networks:
      - media_net
    labels:
      caddy: ${DOMAIN}
      caddy.handle_path: /qbit*
      caddy.handle_path.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/prowlarr:/config
    networks:
      - media_net
    ports:
      - 9696:9696 # Temporary
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /prowlarr*
      caddy.handle.reverse_proxy: "{{upstreams 9696}}"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    networks:
      - media_net
    ports:
      - 7878:7878 # Temporary
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /radarr*
      caddy.handle.reverse_proxy: "{{upstreams 7878}}"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    networks:
      - media_net
    ports:
      - 8989:8989 # Temporary
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /sonarr*
      caddy.handle.reverse_proxy: "{{upstreams 8989}}"
    restart: unless-stopped
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ND_BASEURL=/navidrome # Sets Base URL automatically
    volumes:
      - ${CONF_PATH}/navidrome:/data
      - ${DATA_PATH}/media/music:/music:ro # Read-only access to media
    networks:
      - media_net
    ports:
      - 4533:4533 # Temp
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /navidrome*
      caddy.handle.reverse_proxy: "{{upstreams 4533}}"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/jellyfin:/config
      - ${DATA_PATH}/media:/data/media
    networks:
      - media_net
    ports:
      - 8096:8096 # LEAVE OPEN FOR LOCAL SMART TV
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /jellyfin*
      caddy.handle.reverse_proxy: "{{upstreams 8096}}"
    restart: unless-stopped
  lidarr-downloader:
    image: angrido/lidarr-downloader:latest
    container_name: lidarr-downloader
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LIDARR_URL=http://lidarr:8686
      - LIDARR_API_KEY=fa2e0420bc5944bd8e79ef95f1183f56 # Replace with Lidarr API Key
      - DOWNLOAD_PATH=/downloads/ytlidarr
      - LIDARR_PATH=/music
      - UMASK=002
    volumes:
      - ${CONF_PATH}/lidarr-downloader:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/media/music:/music
    networks:
      - media_net
    ports:
      - 5005:5000
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /lidarr-dl*
      caddy.handle.reverse_proxy: "{{upstreams 5000}}"
    restart: unless-stopped  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOMEPAGE_VAR_DOMAIN=${DOMAIN}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN},100.78.14.119,192.168.1.54
    volumes:
      - ${CONF_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required for Docker stats integration
    networks:
      - media_net
    ports:
      - 3000:3000 # Temp
    labels:
      caddy: ${DOMAIN}
      #caddy.handle: /home*
      caddy.handle.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    networks:
      - media_net
    restart: unless-stopped

    
networks:
  media_net:
    name: media_net
    external: false
